nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-remove-postinstall.cjs
  - path: .yarn/plugins/plugin-remove-workspaces-field.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
